import { CONNECTOR_STATUS } from "./constants";
import { CONNECTOR_STATUS_TYPE } from "./interfaces";

export const CONNECTED_STATUSES: CONNECTOR_STATUS_TYPE[] = [CONNECTOR_STATUS.CONNECTED, CONNECTOR_STATUS.AUTHORIZED];

export const CAN_AUTHORIZE_STATUSES: CONNECTOR_STATUS_TYPE[] = [
  CONNECTOR_STATUS.AUTHORIZING,
  CONNECTOR_STATUS.AUTHORIZED,
  CONNECTOR_STATUS.CONNECTED,
];
